import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { it } from 'node:test';
const require = createRequire(import.meta.url);
const { setup, account, position, flush, act } = require('../../../test/homeDiscoveryHarness.cjs');

for (const mode of ['general', 'season']) it(`${mode}: refresh covers context, current HOT and expanded holdings, retaining disclosures and scope`, async t => {
  const h = setup(mode); t.after(h.close); await flush();
  const trend = () => h.renderer.root.findByType('Trend');
  assert.equal(h.requests.some(r => r.section === 'equity'), false);
  h.requests.length = 0; await h.refresh();
  assert.deepEqual(h.requests.map(r => r.section).sort(), ['hot', 'me', 'portfolio', 'positions', ...(mode === 'season' ? ['ranking'] : [])].sort());
  assert.equal(h.requests.find(r => r.section === 'hot').sortRefresh, true);
  assert.equal(h.requests.find(r => r.section === 'positions').limit, 1);
  act(() => trend().props.onToggle()); await flush();
  act(() => trend().props.onRangeChange('90d')); await flush();
  await h.press('home-holdings-toggle'); await h.press('home-hot-tab-us_stock');
  h.requests.length = 0; await h.refresh();
  assert.equal(trend().props.expanded, true); assert.equal(trend().props.range, '90d');
  assert.equal(h.node('home-holdings-toggle').props.accessibilityState.expanded, true);
  assert.equal(h.rows().length, 7);
  assert.deepEqual(h.requests.filter(r => r.section === 'positions').map(r => r.limit), [1, 100]);
  assert.equal(h.requests.find(r => r.section === 'hot').assetType, 'us_stock');
  assert.equal(h.requests.find(r => r.section === 'hot').sortRefresh, true);
  assert.equal(h.requests.find(r => r.section === 'equity').range, '90d');
  h.beforeRead = async () => { throw new Error('offline'); };
  await h.refresh();
  assert.equal(trend().props.expanded, true); assert.equal(h.rows().length, 7);
  assert.equal(h.hotRows().length, 5);
  assert.equal(h.renderer.root.findByType('ScrollView').props.refreshControl.props.refreshing, false);
  assert.equal(h.renderer.root.findByType('Hero').props.summary.totalAssetKrw, mode);
  let release; const gate = new Promise(resolve => { release = resolve; });
  h.beforeRead = async r => { if (r.account === mode) await gate; };
  await h.refresh();
  h.positions.next = [position(0, 'next')]; await h.switch(account('general', 'next'));
  assert.equal(h.renderer.root.findByType('Hero').props.summary.totalAssetKrw, 'next');
  await act(async () => release()); await flush();
  assert.equal(h.renderer.root.findByType('Hero').props.summary.totalAssetKrw, 'next');
  assert.equal(trend().props.expanded, false); assert.equal(h.rows()[0].props.testID, 'home-position-item-next-a0');
  assert.equal(h.node('home-hot-tab-us_stock').props.accessibilityState.selected, true);
});
