export const ERROR_CODE = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_NICKNAME: 'INVALID_NICKNAME',
  INVALID_PROFILE_IMAGE_URL: 'INVALID_PROFILE_IMAGE_URL',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  AUTH_SIGNUP_CONFLICT: 'AUTH_SIGNUP_CONFLICT',
  AUTH_CONFIGURATION_ERROR: 'AUTH_CONFIGURATION_ERROR',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  GONE: 'GONE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',

  SEASON_NOT_JOINED: 'SEASON_NOT_JOINED',
  SEASON_NOT_ACTIVE: 'SEASON_NOT_ACTIVE',
  SEASON_ALREADY_JOINED: 'SEASON_ALREADY_JOINED',
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',

  MARKET_CLOSED: 'MARKET_CLOSED',
  MARKET_CALENDAR_UNAVAILABLE: 'MARKET_CALENDAR_UNAVAILABLE',
  INVALID_PRICE: 'INVALID_PRICE',
  PRICE_STALE: 'PRICE_STALE',
  ASSET_PRICE_UNAVAILABLE: 'ASSET_PRICE_UNAVAILABLE',
  FX_RATE_STALE: 'FX_RATE_STALE',
  FX_RATE_UNAVAILABLE: 'FX_RATE_UNAVAILABLE',

  QUOTE_REQUIRED: 'QUOTE_REQUIRED',
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  QUOTE_NOT_ACTIVE: 'QUOTE_NOT_ACTIVE',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  QUOTE_MISMATCH: 'QUOTE_MISMATCH',
  RATE_CHANGED_REQUOTE_REQUIRED: 'RATE_CHANGED_REQUOTE_REQUIRED',

  IDEMPOTENCY_REQUIRED: 'IDEMPOTENCY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  ORDER_IDEMPOTENCY_CONFLICT: 'ORDER_IDEMPOTENCY_CONFLICT',

  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_QUANTITY: 'INSUFFICIENT_QUANTITY',

  ASSET_NOT_TRADABLE: 'ASSET_NOT_TRADABLE',
  ORDER_REJECTED: 'ORDER_REJECTED',
  EXCHANGE_REJECTED: 'EXCHANGE_REJECTED',
  RANKING_SNAPSHOT_CHANGED: 'RANKING_SNAPSHOT_CHANGED',

  ORDER_TYPE_NOT_SUPPORTED: 'ORDER_TYPE_NOT_SUPPORTED',
  ORDER_CANCEL_NOT_SUPPORTED: 'ORDER_CANCEL_NOT_SUPPORTED',
  LIMIT_ORDER_DISABLED: 'LIMIT_ORDER_DISABLED',
  LIMIT_BUY_ONLY: 'LIMIT_BUY_ONLY',
  INVALID_LIMIT_PRICE: 'INVALID_LIMIT_PRICE',
  INSUFFICIENT_AVAILABLE_BALANCE: 'INSUFFICIENT_AVAILABLE_BALANCE',
  ORDER_RESERVATION_CONFLICT: 'ORDER_RESERVATION_CONFLICT',
  ORDER_RESERVATION_INCONSISTENT: 'ORDER_RESERVATION_INCONSISTENT',
  ORDER_NOT_CANCELABLE: 'ORDER_NOT_CANCELABLE',
  ORDER_CANCEL_CONFLICT: 'ORDER_CANCEL_CONFLICT',
  // The order-masking 404: an unknown orderId and another account's orderId
  // are deliberately the same response. Without this entry the cancel flow
  // rendered "알 수 없는 서버 오류입니다. code=ORDER_NOT_FOUND" (작업 10 §B-7).
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // TradingAccount surface (작업 9). The integrity codes are listed so a
  // generic error screen renders real Korean copy instead of
  // "알 수 없는 서버 오류입니다. code=…"; they are still routed to the dedicated
  // integrity state by `classifyAccountError`.
  TRADING_ACCOUNT_NOT_FOUND: 'TRADING_ACCOUNT_NOT_FOUND',
  TRADING_ACCOUNT_NOT_ACTIVE: 'TRADING_ACCOUNT_NOT_ACTIVE',
  TRADING_ACCOUNT_INTEGRITY: 'TRADING_ACCOUNT_INTEGRITY',
  TRADING_ACCOUNT_SCOPE_MISMATCH: 'TRADING_ACCOUNT_SCOPE_MISMATCH',
  TRADING_SCOPE_REPAIR_REQUIRED: 'TRADING_SCOPE_REPAIR_REQUIRED',
  TRADING_ACCOUNT_LINK_INTEGRITY: 'TRADING_ACCOUNT_LINK_INTEGRITY',
  FINANCIAL_SCOPE_REPAIR_REQUIRED: 'FINANCIAL_SCOPE_REPAIR_REQUIRED',
  FINANCIAL_TRADING_ACCOUNT_SCOPE_MISMATCH:
    'FINANCIAL_TRADING_ACCOUNT_SCOPE_MISMATCH',
  GENERAL_ACCOUNT_INTEGRITY: 'GENERAL_ACCOUNT_INTEGRITY',
  GENERAL_PERFORMANCE_NOT_INITIALIZED: 'GENERAL_PERFORMANCE_NOT_INITIALIZED',
  GENERAL_PERFORMANCE_INTEGRITY: 'GENERAL_PERFORMANCE_INTEGRITY',
  GENERAL_PERFORMANCE_DISCONTINUITY: 'GENERAL_PERFORMANCE_DISCONTINUITY',
  SEASON_RANKING_SCOPE_REPAIR_REQUIRED: 'SEASON_RANKING_SCOPE_REPAIR_REQUIRED',
  SEASON_RANKING_SCOPE_MISMATCH: 'SEASON_RANKING_SCOPE_MISMATCH',
  SEASON_RANKING_SOURCE_SCOPE_REPAIR_REQUIRED:
    'SEASON_RANKING_SOURCE_SCOPE_REPAIR_REQUIRED',
  SEASON_RANKING_SOURCE_SCOPE_MISMATCH: 'SEASON_RANKING_SOURCE_SCOPE_MISMATCH',
  FINAL_RESULTS_INTEGRITY: 'FINAL_RESULTS_INTEGRITY',
  AD_REWARD_CLAIM_INTEGRITY: 'AD_REWARD_CLAIM_INTEGRITY',
  GENERAL_ACCOUNT_TRADING_NOT_IMPLEMENTED:
    'GENERAL_ACCOUNT_TRADING_NOT_IMPLEMENTED',
  GENERAL_ACCOUNT_FX_NOT_IMPLEMENTED: 'GENERAL_ACCOUNT_FX_NOT_IMPLEMENTED',
  // Settlement produced a tier assignment that disagrees with the final
  // ranking. Structural damage, and routed to the integrity state.
  FINAL_TIER_ASSIGNMENT_CONFLICT: 'FINAL_TIER_ASSIGNMENT_CONFLICT',
  // A TRANSIENT external dependency, NOT damage and NOT a capability limit:
  // the ad provider could not be reached. It must not share copy with either
  // (작업 10 §B-7).
  AD_REWARD_PROVIDER_UNAVAILABLE: 'AD_REWARD_PROVIDER_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
