export const ERROR_CODE = {

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  SEASON_NOT_JOINED: 'SEASON_NOT_JOINED',
  SEASON_NOT_ACTIVE: 'SEASON_NOT_ACTIVE',
  SEASON_ALREADY_JOINED: 'SEASON_ALREADY_JOINED',

  MARKET_CLOSED: 'MARKET_CLOSED',
  INVALID_PRICE: 'INVALID_PRICE',
  PRICE_STALE: 'PRICE_STALE',
  FX_RATE_STALE: 'FX_RATE_STALE',

  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_QUANTITY: 'INSUFFICIENT_QUANTITY',

  ASSET_NOT_TRADABLE: 'ASSET_NOT_TRADABLE',
  ORDER_REJECTED: 'ORDER_REJECTED',
  EXCHANGE_REJECTED: 'EXCHANGE_REJECTED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];