export const ERROR_CODE = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_NICKNAME: 'INVALID_NICKNAME',
  INVALID_PROFILE_IMAGE_URL: 'INVALID_PROFILE_IMAGE_URL',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  AUTH_SIGNUP_CONFLICT: 'AUTH_SIGNUP_CONFLICT',
  AUTH_CONFIGURATION_ERROR: 'AUTH_CONFIGURATION_ERROR',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  GONE: 'GONE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',

  SEASON_NOT_JOINED: 'SEASON_NOT_JOINED',
  SEASON_NOT_ACTIVE: 'SEASON_NOT_ACTIVE',
  SEASON_ALREADY_JOINED: 'SEASON_ALREADY_JOINED',
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',

  MARKET_CLOSED: 'MARKET_CLOSED',
  MARKET_CALENDAR_UNAVAILABLE: 'MARKET_CALENDAR_UNAVAILABLE',
  INVALID_PRICE: 'INVALID_PRICE',
  PRICE_STALE: 'PRICE_STALE',
  ASSET_PRICE_UNAVAILABLE: 'ASSET_PRICE_UNAVAILABLE',
  FX_RATE_STALE: 'FX_RATE_STALE',
  FX_RATE_UNAVAILABLE: 'FX_RATE_UNAVAILABLE',

  QUOTE_REQUIRED: 'QUOTE_REQUIRED',
  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  QUOTE_NOT_ACTIVE: 'QUOTE_NOT_ACTIVE',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  QUOTE_MISMATCH: 'QUOTE_MISMATCH',
  RATE_CHANGED_REQUOTE_REQUIRED: 'RATE_CHANGED_REQUOTE_REQUIRED',

  IDEMPOTENCY_REQUIRED: 'IDEMPOTENCY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  ORDER_IDEMPOTENCY_CONFLICT: 'ORDER_IDEMPOTENCY_CONFLICT',

  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_QUANTITY: 'INSUFFICIENT_QUANTITY',

  ASSET_NOT_TRADABLE: 'ASSET_NOT_TRADABLE',
  ORDER_REJECTED: 'ORDER_REJECTED',
  EXCHANGE_REJECTED: 'EXCHANGE_REJECTED',
  RANKING_SNAPSHOT_CHANGED: 'RANKING_SNAPSHOT_CHANGED',

  ORDER_TYPE_NOT_SUPPORTED: 'ORDER_TYPE_NOT_SUPPORTED',
  ORDER_CANCEL_NOT_SUPPORTED: 'ORDER_CANCEL_NOT_SUPPORTED',
  LIMIT_ORDER_DISABLED: 'LIMIT_ORDER_DISABLED',
  LIMIT_BUY_ONLY: 'LIMIT_BUY_ONLY',
  INVALID_LIMIT_PRICE: 'INVALID_LIMIT_PRICE',
  INSUFFICIENT_AVAILABLE_BALANCE: 'INSUFFICIENT_AVAILABLE_BALANCE',
  ORDER_RESERVATION_CONFLICT: 'ORDER_RESERVATION_CONFLICT',
  ORDER_RESERVATION_INCONSISTENT: 'ORDER_RESERVATION_INCONSISTENT',
  ORDER_NOT_CANCELABLE: 'ORDER_NOT_CANCELABLE',
  ORDER_CANCEL_CONFLICT: 'ORDER_CANCEL_CONFLICT',
  LIMIT_ORDER_MATCHER_UNAVAILABLE: 'LIMIT_ORDER_MATCHER_UNAVAILABLE',
  LIMIT_ORDER_EVENT_STREAM_UNAVAILABLE: 'LIMIT_ORDER_EVENT_STREAM_UNAVAILABLE',
  // Per-asset provider readiness: the asset itself must be subscribed and
  // acknowledged on the current connection generation, not merely "the socket
  // is up". Distinct codes so the copy can say WHY.
  LIMIT_ORDER_PROVIDER_UNAVAILABLE: 'LIMIT_ORDER_PROVIDER_UNAVAILABLE',
  LIMIT_ORDER_PROVIDER_NOT_SUBSCRIBED: 'LIMIT_ORDER_PROVIDER_NOT_SUBSCRIBED',
  LIMIT_ORDER_PROVIDER_SUBSCRIPTION_FAILED:
    'LIMIT_ORDER_PROVIDER_SUBSCRIPTION_FAILED',
  // Readiness PROOF verdicts from inside the create transaction: the
  // pre-check passed but its evidence could not be re-verified (expired,
  // structurally invalid, or the provider connection generation moved).
  LIMIT_ORDER_PROVIDER_READINESS_PROOF_EXPIRED:
    'LIMIT_ORDER_PROVIDER_READINESS_PROOF_EXPIRED',
  LIMIT_ORDER_PROVIDER_READINESS_PROOF_INVALID:
    'LIMIT_ORDER_PROVIDER_READINESS_PROOF_INVALID',
  LIMIT_ORDER_PROVIDER_GENERATION_CHANGED:
    'LIMIT_ORDER_PROVIDER_GENERATION_CHANGED',
  // Path-B (closed-candle safety net) health. Separate from the matcher codes
  // above: these mean the SAFETY NET under automatic matching is not whole, so
  // new limit registration is refused while existing orders, cancel and
  // cleanup keep working.
  LIMIT_ORDER_CANDLE_RECONCILIATION_UNAVAILABLE:
    'LIMIT_ORDER_CANDLE_RECONCILIATION_UNAVAILABLE',
  LIMIT_ORDER_CANDLE_RECONCILIATION_STALE:
    'LIMIT_ORDER_CANDLE_RECONCILIATION_STALE',
  LIMIT_ORDER_CANDLE_RECONCILIATION_BACKLOG_EXCEEDED:
    'LIMIT_ORDER_CANDLE_RECONCILIATION_BACKLOG_EXCEEDED',
  LIMIT_ORDER_CANDLE_RECONCILIATION_GAP_DETECTED:
    'LIMIT_ORDER_CANDLE_RECONCILIATION_GAP_DETECTED',
  LIMIT_ORDER_CANDLE_RESERVATION_MISMATCH:
    'LIMIT_ORDER_CANDLE_RESERVATION_MISMATCH',
  // Asset-scoped safety-net codes: the failure names ONE asset, so only that
  // asset's new limit registration pauses; other assets keep working.
  LIMIT_ORDER_CANDLE_ASSET_GAP_DETECTED:
    'LIMIT_ORDER_CANDLE_ASSET_GAP_DETECTED',
  LIMIT_ORDER_CANDLE_FINALIZER_STALE: 'LIMIT_ORDER_CANDLE_FINALIZER_STALE',
  LIMIT_ORDER_CANDLE_ASSET_BACKLOG_EXCEEDED:
    'LIMIT_ORDER_CANDLE_ASSET_BACKLOG_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
