/** Reviewed product copy, independent of error code and diagnostic vocabulary.
 * Exact matches only: neither envelope shape nor technical-word blacklists
 * approve arbitrary exception/Provider/DB prose for users or operators.
 */
const PUBLIC_MESSAGES = new Set<string>([
  'Request could not be completed.',
  'Account information could not be verified. Please try again.',
  'Conditional orders are currently disabled.',
  'Futures user trading is disabled.',
  'Provide one Stop Loss, Take Profit, or one of each.',
  'Invalid protection leg.',
  'Duplicate or invalid protection kind.',
  'Choose Market or Limit execution.',
  'Market child cannot have a limit price.',
  'Price must be a positive decimal string with at most eight decimal places.',
  'A valid idempotency key is required.',
  'Trigger prices must be strictly beyond the current reference price.',
  'This position already has active protection.',
  'Attached entry requires a flat position and no competing entry.',
  'An open position is required.',
  'Cancel existing sell reservations before protecting the whole position.',
  'Futures Limit entry is not supported.',
  'The account trading window ended.',
  'A fresh eligible reference price is required.',
  'Protection changed before execution.',
  'An attached entry already owns this position.',
  'Cancel the pending protection child before increasing.',
  'Cancel protection before placing a separate Limit sell.',
  'Specify a product, asset, and open position.',
  'The account cannot create protection now.',
  'Protection not found.',
  'The command differs from the committed request.',
  'Invalid history query.',
  'Attached protection is supported only on Spot BUY Limit entries.',
  'A conflicting protection intent prevents this increase.',
  'The exit limit is not executable.',
  'Cancel the pending exit before increasing.',
  'Available Futures collateral is insufficient for margin and fees.',
  'Available Futures collateral is insufficient for the required margin and maintenance.',
  'Check the instrument, operation, direction, quantity, leverage and position.',
  'Close the existing one-way position before opening another.',
  'Direction must match the existing one-way position.',
  'Futures collateral could not be settled. Please try again.',
  'Futures collateral information could not be verified.',
  'Futures wallet information could not be verified.',
  'Futures instrument was not found.',
  'Futures trading is disabled.',
  'This Futures instrument is not yet available for new trades.',
  'Leverage is fixed for the open position lifetime.',
  'Leverage must be an integer from 1 through 100.',
  'Loss and fee cannot settle safely without liquidation.',
  'Margin mode is fixed for the position lifetime.',
  'Only risk-reducing Futures trades are enabled.',
  'Pagination is outside the supported range.',
  'Reduce quantity cannot exceed the position; close must match it exactly.',
  'Season participant is excluded.',
  'The current Mark Price is unavailable for risk evaluation. Please try again.',
  'The current execution price is unavailable. Please try again.',
  'The intended open position was not found.',
  'The position would not meet maintenance requirements.',
  'The requested trade exceeds the supported amount range.',
  'The trade amount is below the supported minimum.',
  'This Futures instrument is not available for trading.',
  'This request conflicts with an earlier Futures command.',
  'This trade would spend collateral protected for Cross positions.',
  'Trading account is not active.',
  'Trading fees could not be verified. Please try again.',
  'Transfer would spend isolated Futures collateral.',
  'Asset is inactive.',
  'Asset is not active.',
  'Asset is not tradable.',
  'Asset not found.',
  'Asset price is unavailable.',
  'Available position quantity is insufficient.',
  'Cash wallet balance is insufficient.',
  'FX rate changed; requote is required',
  'FX rate changed; requote is required.',
  'FX rate is stale',
  'FX rate is stale.',
  'FX rate is unavailable',
  'FX rate is unavailable.',
  'Idempotency key conflicts with a different request',
  'Idempotency key is required',
  'Idempotency key is too long.',
  'Idempotent request has failed',
  'Idempotent request is still pending',
  'Insufficient balance',
  'Invalid amount',
  'Invalid credentials.',
  'Invalid currency pair',
  'Invalid currency.',
  'Invalid currencyCode.',
  'Invalid decimal string',
  'Invalid direction.',
  'Invalid order side.',
  'Invalid order status.',
  'Invalid orderType.',
  'Invalid refresh token.',
  'KRX market is closed.',
  'No executable market liquidity is available; try a new quote.',
  'Only USD/KRW is supported.',
  'Only market orders are supported.',
  'Only submitted orders can be executed.',
  'Order not found.',
  'Order position was not found.',
  'Order price changed; requote is required.',
  'Order request body is required.',
  'Position quantity is insufficient.',
  'Price is stale.',
  'Provide amount or quantity, never both.',
  'Quote does not match the execute request',
  'Quote does not match the order create request.',
  'Quote does not match the submitted order.',
  'Quote has expired',
  'Quote has expired.',
  'Quote is not active',
  'Quote is not active.',
  'Quote not found',
  'Quote not found.',
  'Ranking snapshot changed. Please reload from the first page.',
  'Refresh the list from the first page.',
  'Same idempotencyKey was used with a different order create request.',
  'Season already joined',
  'Season has ended',
  'Season has ended.',
  'Season has not started',
  'Season has not started.',
  'Season is not active',
  'Season is not active.',
  'Season is not joined',
  'Season is not joined.',
  'Season not found',
  'Season not found.',
  'Season participant is excluded',
  'Season participant is excluded from FX.',
  'Season participant is excluded from trading.',
  'Season participant is not active',
  'Season participant is not active.',
  'Season participant not found.',
  'Source wallet not found',
  'Target wallet not found',
  'This quote was already used by a different order create request.',
  'Trading account is not active',
  'Trading account not found.',
  'US market is closed.',
  'User is not active',
  'User is not active.',
  'User not found.',
  'idempotencyKey is required.',
  'limit must be a positive integer.',
  'limit must be greater than 0.',
  'offset must be a non-negative integer.',
  'orderId is required.',
  'quoteId is required',
  'quoteId is required for order execution.',
  'quoteId is required.',
]);

export function safePublicErrorMessage(value: unknown): string | undefined {
  return typeof value === 'string' && PUBLIC_MESSAGES.has(value)
    ? value
    : undefined;
}
