import { STATUS_CODES } from 'node:http';

/** Reviewed fixed domain copy only. Error/envelope shape is not a trust signal.
 * Runtime/Provider/DB prose must never be admitted by prefix. The only template
 * below is ProviderHttpClient's finite provider/status/category vocabulary.
 * This catalog affects diagnostic projection, not public API codes or branching.
 */
const SAFE_MESSAGES = new Set<string>([
  ...Object.values(STATUS_CODES).filter(
    (message): message is string => typeof message === 'string',
  ),
  // F1/F2 fixed product/domain copy; no runtime amount or Provider/DB prose.
  'Request could not be completed.',
  'Background operation failed.',
  'Job failed.',
  'Daily season cycle failed.',
  'Provider FX ingestion failed.',
  'Provider Binance ingestion failed.',
  'Provider KIS REST current price ingestion failed.',
  'Provider KIS WebSocket trade ingestion failed.',
  'snapshotDate must be YYYY-MM-DD.',
  'Account information could not be verified. Please try again.',
  'Available Futures collateral is insufficient for margin and fees.',
  'Available Futures collateral is insufficient for the required margin and maintenance.',
  'Check the instrument, operation, direction, quantity, leverage and position.',
  'Close the existing one-way position before opening another.',
  'Direction must match the existing one-way position.',
  'Futures collateral could not be settled. Please try again.',
  'Futures collateral information could not be verified.',
  'Futures instrument was not found.',
  'Futures trading is disabled.',
  'Season final results require all Futures positions to be closed.',
  'Futures final settlement requires an ended Season.',
  'Season settlement account scope could not be verified.',
  'Final Futures settlement lifecycle could not be verified.',
  'Season wallet set could not be verified.',
  'Release all Season reservations before final settlement.',
  'Protected collateral is underfunded.',
  'Fresh Futures Mark Price is required to value this account.',
  'Futures position scope could not be verified.',
  'Final Futures settlement price is unavailable.',
  'A fresh final execution price at Season end is required.',
  'This Futures instrument is not yet available for new trades.',
  'Season final settlement terms could not be verified.',
  'Final Futures settlement price could not be verified.',
  'Futures wallet information could not be verified.',
  'Leverage is fixed for the open position lifetime.',
  'Leverage must be an integer from 1 through 100.',
  'Loss and fee cannot settle safely without liquidation.',
  'Margin mode is fixed for the position lifetime.',
  'Only risk-reducing Futures trades are enabled.',
  'Pagination is outside the supported range.',
  'Reduce quantity cannot exceed the position; close must match it exactly.',
  'Season participant is excluded.',
  'The current Mark Price is unavailable for risk evaluation. Please try again.',
  'The current execution price is unavailable. Please try again.',
  'The intended open position was not found.',
  'The position would not meet maintenance requirements.',
  'The requested trade exceeds the supported amount range.',
  'The trade amount is below the supported minimum.',
  'This Futures instrument is not available for trading.',
  'This request conflicts with an earlier Futures command.',
  'This trade would spend collateral protected for Cross positions.',
  'Trading account is not active.',
  'Trading fees could not be verified. Please try again.',
  'Transfer would spend isolated Futures collateral.',
  '/fx execute write path is not implemented yet.',
  'Admin cannot change their own role.',
  'Admin cannot change their own status.',
  'Admin role is required.',
  'All four canonical cash wallets are required for portfolio valuation.',
  'Allocation cannot be calculated when totalAssetKrw is zero.',
  'Asset is inactive.',
  'Asset is not active.',
  'Asset is not tradable.',
  'Asset market is unsupported for KIS domestic stock candles.',
  'Asset market is unsupported for KIS overseas stock candles.',
  'Asset not found.',
  'Asset price is unavailable.',
  'Asset price snapshot is stale.',
  'Asset price snapshot is unavailable.',
  'Asset price state could not be built.',
  'Asset type is unsupported for candles.',
  'Auth configuration is invalid.',
  'Auth configuration is missing.',
  'Available position quantity is insufficient.',
  'Batch job idempotency conflict.',
  'Batch job is already running for this idempotency key.',
  'Batch job run not found.',
  'Binance candle provider is unavailable.',
  'Binance returned malformed candle data.',
  'Cannot demote the last active admin.',
  'Cannot suspend or delete the last active admin.',
  'Cash wallet balance is insufficient.',
  'Cash wallet was updated concurrently.',
  'Concurrent wallet update rejected',
  'Conflict',
  'Created order could not be read back.',
  'Crypto candles require a Binance-compatible symbol.',
  'Crypto candles require a USDT quote Binance symbol.',
  'Current season is required for season candle range.',
  'Current season not found',
  'Daily history scope or date is inconsistent.',
  'Database transaction clock is unavailable.',
  'Decimal must be finite',
  'Decimal must be greater than 0',
  'Deleted user role changes are forbidden.',
  'Deleted users must be restored through the restore endpoint.',
  'Domestic stock candles require a 6-digit KIS stock code.',
  'Exactly one non-negative cash wallet per canonical scope/currency is required.',
  'Execute transaction failed',
  'Executed order could not be read back.',
  'Execution source is ineligible',
  'FX execution source is ineligible.',
  'FX rate changed; requote is required',
  'FX rate changed; requote is required.',
  'FX rate is stale',
  'FX rate is stale.',
  'FX rate is unavailable',
  'FX rate is unavailable.',
  'Failed batch jobs require a new idempotencyKey for retry.',
  'Final rank conflicts with another participant.',
  'Final result correction is allowed only for ended or settled seasons.',
  'General account KRW wallet could not be credited under its own account scope.',
  'General account performance service unavailable',
  'General order carries a season participant link.',
  'General order snapshot account is missing or has the wrong mode.',
  'General trading account disappeared while creating an order.',
  'Idempotency key conflicts with a different request',
  'Idempotency key is required',
  'Idempotency key is too long.',
  'Idempotent request has failed',
  'Idempotent request is stale and requires recovery',
  'Idempotent request is still pending',
  'Insufficient balance',
  'Internal server error',
  'Internal server error.',
  'Invalid amount',
  'Invalid asset sort parameters.',
  'Invalid assetType.',
  'Invalid batch job status.',
  'Invalid credentials.',
  'Invalid currency pair',
  'Invalid currency.',
  'Invalid currencyCode.',
  'Invalid decimal string',
  'Invalid direction.',
  'Invalid ledger order reference.',
  'Invalid order side.',
  'Invalid order status.',
  'Invalid orderType.',
  'Invalid rankType.',
  'Invalid ranking scope.',
  'Invalid records type.',
  'Invalid refresh token.',
  'Invalid reward fulfillment status.',
  'Invalid reward type.',
  'Invalid season status.',
  'Invalid seasonStatus.',
  'Invalid txType.',
  'Invalid user role.',
  'Invalid user status.',
  'Invalid wallet transfer reference.',
  'KIS candle provider is unavailable.',
  'KIS returned an error for candle data.',
  'KRX market is closed.',
  'Ledger order reference is missing or inconsistent.',
  'Ledger wallet transfer reference is missing or inconsistent.',
  'Limit order cancel service is not wired.',
  'Limit order create service is not wired.',
  'Limit orders cannot be executed through the order execute path.',
  'Limit-order matching failed.',
  'Market calendar coverage is unavailable for the candle range.',
  'Market quote has no valid pinned fee rate; requote is required.',
  'Market session override not found.',
  'Moderation text fields must be strings.',
  'No approved admin_manual USD/KRW FX rate snapshot is available.',
  'No eligible USD/KRW FX rate snapshot is available.',
  'No executable market liquidity is available; try a new quote.',
  'Only USD/KRW is supported.',
  'Only deleted users can be restored.',
  'Only market orders are supported.',
  'Only submitted orders can be executed.',
  'Operator role is required.',
  'Ops job failed.',
  'Order cancel is not supported for MVP market orders.',
  'Order cash wallet was not found.',
  'Order execution conflicted with another state change.',
  'Order execution source is ineligible.',
  'Order execution transaction failed.',
  'Order has no canonical trading account scope.',
  'Order idempotency conflict.',
  'Order not found.',
  'Order position was not found.',
  'Order price changed; requote is required.',
  'Order request body is required.',
  'Order settlement currency does not match order currency.',
  'Order trading-account relation does not match its account scope.',
  'Participant account changed during FX execution.',
  'Participant has no trading account link; run trading-accounts:repair-links.',
  'Participant trading account changed during execution.',
  'Portfolio account ownership mismatch.',
  'Portfolio valuation service unavailable',
  'Position belongs to a different trading account.',
  'Position currency does not match order currency.',
  'Position for the limit sell was not found.',
  'Position has no canonical trading account scope.',
  'Position quantity is insufficient.',
  'Position scope does not match the limit sell account.',
  'Position scope does not match the limit-order trading account.',
  'Position was updated concurrently.',
  'Price is stale.',
  'Provide amount or quantity, never both.',
  'Provider FX rate is stale',
  'Provider FX rate is stale.',
  'Provider FX rate is unavailable',
  'Provider FX rate is unavailable.',
  'Provider asset price is stale.',
  'Provider asset price is unavailable.',
  'Provider execution source is required',
  'Provider ingestion trigger failed.',
  'Quote does not match the execute request',
  'Quote does not match the order create request.',
  'Quote does not match the submitted order.',
  'Quote has expired',
  'Quote has expired.',
  'Quote is not active',
  'Quote is not active.',
  'Quote not found',
  'Quote not found.',
  'Ranking snapshot changed. Please reload from the first page.',
  'Refresh the list from the first page.',
  'Reward code is too long.',
  'Reward fulfillment already exists for this target and reward code.',
  'Reward fulfillment cannot be canceled from its current status.',
  'Reward fulfillment cannot be fulfilled from its current status.',
  'Reward fulfillment idempotency key conflicts with a different request.',
  'Reward fulfillment not found.',
  'Reward fulfillment requires a settled season.',
  'Reward has already been fulfilled for this participant.',
  'Reward name is too long.',
  'Reward target user must be active.',
  'Same idempotencyKey was used with a different order create request.',
  'Season account has no participant.',
  'Season already joined',
  'Season has ended',
  'Season has ended.',
  'Season has not started',
  'Season has not started.',
  'Season is not active',
  'Season is not active.',
  'Season is not joined',
  'Season is not joined.',
  'Season not found',
  'Season not found.',
  'Season order account and participant link do not agree.',
  'Season order has no fee source.',
  'Season order has no season participant.',
  'Season order has no valid participant account link; run trading-accounts:repair-links.',
  'Season participant does not belong to the requested season.',
  'Season participant does not match its canonical account owner/capital.',
  'Season participant does not match the fulfillment request.',
  'Season participant exclusion is allowed only for active or ended seasons.',
  'Season participant has no trading account link; run trading-accounts:repair-links before writing performance snapshots.',
  'Season participant is already excluded.',
  'Season participant is excluded',
  'Season participant is excluded from FX.',
  'Season participant is excluded from trading.',
  'Season participant is not active',
  'Season participant is not active.',
  'Season participant is not linked to its canonical season trading account.',
  'Season participant not found.',
  'Season trading account has no participant link.',
  'Separate price and settlement currencies are not supported for order execution yet.',
  'Separate price and settlement currencies are not supported for portfolio valuation yet.',
  'Some daily snapshots could not be generated; the next scheduled tick retries missing rows.',
  'Sort snapshot does not match the requested filters.',
  'Sorted pagination requires sortSnapshot.',
  'Sorting requires withPrice=true.',
  'Source wallet not found',
  'Stored 5m baseline coverage is being prepared for this candle range.',
  'Suspended users cannot be promoted to operator or admin.',
  'Target user already has the requested role.',
  'Target user already has the requested status.',
  'Target user not found.',
  'Target wallet not found',
  'The canonical cash wallet set is incomplete or invalid; investigate explicitly. Reads never create wallets.',
  'This quote was already used by a different order create request.',
  'Trade fee rate makes net amount negative.',
  'Trade fee rate makes order net amount negative.',
  'Trading account access service unavailable',
  'Trading account does not have a valid owner scope for its mode.',
  'Trading account is not active',
  'Trading account not found.',
  'Transaction failed.',
  'Trusted execution evidence is unavailable; try again later.',
  'US market is closed.',
  'US stock candles require a KIS-compatible stock symbol.',
  'USD/KRW FX rate must be greater than 0.',
  'USD/KRW FX rate snapshot is not yet effective.',
  'USD/KRW FX rate snapshot is required for USD conversion.',
  'USD/KRW FX rate snapshot is stale.',
  'USD/KRW FX rate snapshot is unavailable.',
  'USD/KRW execution rate is required for realizedPnlKrw.',
  'Unauthorized',
  'User is not active',
  'User is not active.',
  'User not found.',
  'capturedAt must be a UTC ISO 8601 timestamp.',
  'currencyCode must match asset settlementCurrency.',
  'custom overrides require both openTime and closeTime.',
  'date must be a valid calendar date.',
  'date must use YYYY-MM-DD format.',
  'finalRank must be a positive safe integer.',
  'finalRank or finalTier is required.',
  'finalTier must be a non-empty string or null.',
  'from must not be after to.',
  'granularity must be daily when supplied.',
  'hidden must be a boolean.',
  'idempotencyKey is required.',
  'includeClosed must be true or false.',
  'includePrevious must be true or false.',
  'initialCapitalKrw must be greater than 0.',
  'limit must be a positive integer.',
  'limit must be greater than 0.',
  'localDate must be a valid YYYY-MM-DD calendar date.',
  'market must be KRX or US.',
  'market must be KRX, US, CRYPTO, or ALL.',
  'offset must be a non-negative integer.',
  'openTime must be earlier than closeTime.',
  'orderId is required.',
  'overrideType must be regular, closed, or custom.',
  'quoteId is required',
  'quoteId is required for order execution.',
  'quoteId is required.',
  'range must be one of 1d, 3d, 7d, 14d, 30d, prev_open, prev2_open, 1y, or season.',
  'range must be one of 1d, 7d, 30d, 90d, 180d, 360d, all.',
  'range must be one of 1d, 7d, season.',
  'rankingDate must be YYYY-MM-DD.',
  'refresh must be true or false',
  'regular and closed overrides must not include session times.',
  'regular and custom overrides are not supported on weekends.',
  'to must be HHmmss or an ISO datetime.',
]);

export function safeDiagnosticMessage(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  if (SAFE_MESSAGES.has(value)) return value;
  // Exact safe factory templates, not arbitrary ProviderHttpError.message.
  const provider = '(?:binance|kis|exchange_rate_api|korea_exim_exchange_rate)';
  return new RegExp(
    `^${provider} (?:HTTP [1-5][0-9]{2} \\(PROVIDER_HTTP_ERROR\\)|returned invalid JSON \\(PROVIDER_JSON_PARSE_ERROR\\)|request failed \\(PROVIDER_(?:TIMEOUT|REQUEST_FAILED)\\))\\.$`,
    'u',
  ).test(value)
    ? value
    : undefined;
}
